# Generated by Django 3.1.2 on 2020-10-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='React',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reguler', models.CharField(max_length=500)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
